# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mudak
tagline:          'Yet another tech blog...'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.mudak.fr
baseurl:          /

author:
  name:           'Jean-Philippe Briend'
  url:            https://twitter.com/jpbriend

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jpbriend/jpbriend.github.io
